name: Manual Test Pipeline

on:
  workflow_dispatch:
    inputs:
      paper_limit:
        description: 'Max papers per topic (for quick testing)'
        required: false
        default: '5'
        type: string
      enable_email:
        description: 'Enable email sending'
        required: false
        default: false
        type: boolean

jobs:
  test-pipeline:
    name: Test Pipeline Execution
    runs-on: ubuntu-latest
    
    # Required for optional GitHub Pages deployment
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pipeline (test mode)
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          API_KEY: ${{ secrets.API_KEY }}
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        run: |
          if [ "${{ github.event.inputs.paper_limit }}" != "" ]; then
            python src/main.py --paper-limit ${{ github.event.inputs.paper_limit }}
          else
            python src/main.py
          fi

      - name: Check generated output
        if: always()
        run: |
          echo "=== Generated site structure ==="
          if [ -d site ]; then
            tree site -L 2 || find site -maxdepth 2
            echo ""
            echo "=== Manifest content ==="
            if [ -f site/manifest.json ]; then
              cat site/manifest.json
            fi
            echo ""
            echo "✅ Site directory generated successfully"
          else
            echo "❌ Site directory not generated"
            exit 1
          fi

      - name: Upload test artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-site-output
          path: site
          if-no-files-found: warn
          retention-days: 7
          
      - name: Deploy to GitHub Pages (optional)
        if: success() && github.event.inputs.enable_email == 'true'
        uses: actions/upload-pages-artifact@v3
        with:
          path: site
          
      - name: Deploy Pages
        if: success() && github.event.inputs.enable_email == 'true'
        id: deployment
        uses: actions/deploy-pages@v4
